name: scrape

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      OVERCAST_COOKIE: ${{ secrets.OVERCAST_COOKIE }}
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - run: ls -l
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - run: python -m pip install overcast-to-sqlite
    - run: python -m overcast_to_sqlite.cli save -v
    - run: python -m overcast_to_sqlite.cli extend -v
    - run: ls -l
    - run: python -m overcast_to_sqlite.cli html
    - name: Commit and push
      if: success() || failure()
      run: |-
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
